config/routes.rb
Rails.application.routes.draw do
  
  resources :class_rooms
  resources :class_plans
  resources :school_days
  resources :animals
  resources :payment_types
  resources :services
  resources :service_types
  
  resources :purchase_items
  resources :purchases
  resources :materials
  resources :material_categories
  resources :bank_accounts
  resources :providers
  resources :banks
  
  
  resources :taxes
  resources :deductions
  resources :benefits
  resources :benefit_types
  resources :employments
  resources :registrations   
  resources :document_types
  
  resources :people do
    resources :employments 
    resources :registrations   
  end
  
 
  resources :cities
  resources :countries
  resources :menu_items
  resources :phone_types
  
  resources :occupations
  resources :settings
  resources :states
  resources :users
  
  devise_for :users, path: 'u'

  post 'utils/postal_code'
  post 'utils/cities'
  get 'utils/cities'

  root 'people#index'
  mount Crono::Web, at: '/crono'
end

app/models/person.rb
class Person < ApplicationRecord
  has_ancestry

  has_one_attached :photo
  has_one :account

   # para cadastro dos dependentes nested
   belongs_to :person, inverse_of: :people, optional: true
   has_many :people, inverse_of: :person, dependent: :destroy
   accepts_nested_attributes_for :people, allow_destroy: true
   

  belongs_to :user, optional: true
  belongs_to :city
  belongs_to :place, optional: true
  #belongs_to :county, class_name: "City", foreign_key: "county_id", optional: true
  
  has_many :addresses, dependent: :destroy, as: :addressable
  has_many :phones, dependent: :destroy, as: :phonable
  
  has_many :documents, dependent: :destroy, as: :documentable
  accepts_nested_attributes_for :documents
  

  has_many :employments, dependent: :destroy
  accepts_nested_attributes_for :employments, allow_destroy: true

  has_many :registrations, dependent: :destroy
  accepts_nested_attributes_for :registrations, allow_destroy: true

  accepts_nested_attributes_for :user, allow_destroy: true
  accepts_nested_attributes_for :addresses, allow_destroy: true
  accepts_nested_attributes_for :phones, allow_destroy: true

  #validates :cpf, cpf: true
  validates :name, presence: true
  #validates :registration, :admission, :business_email, :place, presence: { unless: :person }
  validates :user, presence: { unless: :person }
 

  # para jogar dependentes no ancestry
  #before_save :set_parent_id
  


  def full_description
    "#{name} (CPF: #{cpf} )" 
  end


  def age
    now = Time.now.utc.to_date
    now.year - self.birth.year - (self.birth.to_date.change(:year => now.year) > now ? 1 : 0)
  end

 
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  load_and_authorize_resource

  # GET /people
  def index
    @q = Person.ransack(params[:q])
    @people = @q.result(distinct: true).page(params[:page])
  end

  # GET /people/1
  def show
  end

  # GET /people/new
  def new
    @person.addresses.build
    
    @person.build_user
      
    @person.phones.build phone_type: PhoneType.first
    @cities = []
    @cities_address = []
  end

  # GET /people/1/edit
  def edit
    @cities = [ @person.city ]
    @cities_address = @person.addresses.map(&:city)
  end

  # POST /people
  def create
    @person = Person.new(person_params)    

    if @person.save
      redirect_to @person, notice: 'Person was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /people/1
  def update
    if @person.update(person_params)
      redirect_to @person, notice: 'Person was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
    redirect_to people_url, notice: 'Person was successfully destroyed.'
  end

 

  private
    # Only allow a trusted parameter "white list" through.
    def person_params
      params.require(:person).permit(
        :name, :photo, :father, :mother, :birth, :cpf, :rg, :user_id, :city_id, :registration,
        :place_id, :business_email, 
        addresses_attributes: [
            :id, :description, :street, :number, :complement, :district, :zipcode, :city_id, :_destroy
        ],
        phones_attributes: [
            :id, :number, :phone_type_id, :_destroy
        ],
        user_attributes: [
          :id, :_destroy, :name, :email, :password, :_destroy
        ],
        people_attributes: [
          :id, :_destroy, :name, :photo, :father, :mother, :kinship_id, :birth, :cpf, :rg, :city_id
        ],
        documents_attributes: [
          :id, :_destroy, :document_type_id, :attachment
        ]
      )
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_document_fields.html.erb
<div class="document nested-fields">
  <div class='row'>    
    <%= f.association :document_type, collection: DocumentType.order(:name), wrapper_html: { class: 'col-md-3' }  %>

    <%= f.hidden_field :attachment, value: f.object.attachment.signed_id if f.object.attachment.attached? %>
    <%= f.input :attachment, input_html: {
      direct_upload: true, class: 'fileinput', data: { 
        file: (rails_blob_url(f.object.attachment) if f.object.attachment.attached?)
      }
    } %> 

    <div class="col-md-2">
      <%= link_to_remove_association f, class: 'btn btn-danger top-32' do %>
        <i class="fa fa-fw fa-times"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/people/_form.html.erb
<%= simple_form_for(object) do |f| %>

  <div class="card"> 
    <ul class="nav nav-pills nav-justified">
      <li class="nav-item">
        <a class="nav-link active" href="#tab_1" data-toggle="tab">
          <i class="fa fa-home fa-2x"></i> 
          <br>
          Básico
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#tab_2" data-toggle="tab">
          <i class="fa fa-map-marked-alt fa-2x"></i>
          <br>
          Endereço
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#tab_3" data-toggle="tab">
          <i class="fa fa-user fa-2x"></i>
          <br>
          Usuário
        </a>
      </li>
     
      <li class="nav-item">
        <a class="nav-link" href="#tab_5" data-toggle="tab">
          <i class="fa fa-mobile-alt fa-2x"></i>
          <br>
          Contatos
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#tab_6" data-toggle="tab">
          <i class="fa fa-id-card fa-2x"></i>
          <br>
          Documentos
        </a>
      </li>
    </ul>
  </div>

  <div class="tab-content">
    <div class="tab-pane active" id="tab_1">
      <div class="card card-outline card-info">
        <div class="card-header">
          <h3 class="card-title">
            Dados Básicos
          </h3>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-9">
              <%= f.input :name %>
              <%= f.input :mother %>
              <%= f.input :father %>
              <div class="row">
              </div>
              <div class="row">
                <%= f.input :cpf, wrapper_html: { class: 'col-md-3' }, input_html: { class: 'cpf_mask' } %>
                <%= f.input :rg, wrapper_html: { class: 'col-md-3' } %>
                <%= f.input :birth, html5: true, wrapper_html: { class: 'col-3' } %>
                <%= f.association :city, wrapper_html: { class: 'col-md-3' },
                  input_html: { class: 'select2_cities' },
                  collection: @cities
                %>
              </div>
            </div>
            <div class="col-3">
              <%= f.hidden_field :photo, value: f.object.photo.signed_id if f.object.photo.attached? %>
              <%= f.input :photo, input_html: {
                direct_upload: true, class: 'fileinput', data: { 
                  file: (rails_blob_url(f.object.photo) if f.object.photo.attached?)
                }
              } %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="tab-pane" id="tab_2">
      <%= f.simple_fields_for :addresses do |address| %>
        <%= render 'shared/address_fields', f: address %>
      <% end %>
    </div>

    <div class="tab-pane" id="tab_3">
      <%= f.simple_fields_for :user do |user| %>
        <%= render 'shared/user_fields', f: user %>
      <% end %>
    </div>

   

    <div class="tab-pane" id="tab_5">
      <div class="card card-outline card-info">
        <div class="card-header">
          <h3 class="card-title">
            Contatos
          </h3>
        </div>
        <div class="card-body">
         
          
          <div id="phones" class='row'>
            <div class="col-md-12">
              <%= f.simple_fields_for :phones do |fe| %>
                <%= render 'phone_fields', f: fe %>
              <% end %>

              <div class="control-group">
                <div class="controls">
                  <%= link_to_add_association f, :phones do %>
                    <div class="btn btn-success">
                      <i class="fa fa-fw fa-plus"></i> Adicionar Telefone
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="tab-pane" id="tab_6">
      <div class="card card-outline card-info">
        <div class="card-header">
          <h3 class="card-title">
            Documentos
          </h3>
        </div>
        <div class="card-body">
          <div id="documents" class='row'>
            <div class="col-md-12">
              <%= f.simple_fields_for :documents do |fe| %>
                <%= render 'document_fields', f: fe %>
              <% end %>

              <div class="control-group">
                <div class="controls">
                  <%= link_to_add_association f, :documents do %>
                    <div class="btn btn-success">
                      <i class="fa fa-fw fa-plus"></i> Adicionar Documento
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="card card-outline card-info">
    <div class="card-footer">
      <%= f.submit class: "btn btn-info" %>
      <%= link_to 'Cancelar', eval_with_rescue("#{controller_name}_path"), class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/people/_person_fields.html.erb
<div class="card card-info dependent nested-fields">
  <div class="card-header">
    <h3 class="card-title">Dependente</h3>
    <div class="card-tools">
      <%= link_to_remove_association f, class: 'btn btn-tool' do %>
        <i class="fa fa-fw fa-times"></i>
      <% end %>
    </div>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-9">
        <div class="row">
          <%= f.input :name, wrapper_html: { class: 'col-md-9' }  %> 
        
        </div>
        <div class="row">
          <%= f.input :mother, wrapper_html: { class: 'col-md-6' }  %> 
          <%= f.input :father, wrapper_html: { class: 'col-md-6' }  %> 
        </div>
        <div class="row">
          <%= f.input :cpf, wrapper_html: { class: 'col-md-3' } %>
          <%= f.input :rg, wrapper_html: { class: 'col-md-3' } %>
          <%= f.input :birth, html5: true, wrapper_html: { class: 'col-3' } %>
          <%= f.association :city, wrapper_html: { class: 'col-md-3' },
            collection: Proc.new{ City.order(:name).map{ |c| [c.name, c.id, data: { ibge: c.ibgeid }] } }
          %>
        </div>
      </div>
       <div class="col-3">
        <%= f.hidden_field :photo, value: f.object.photo.signed_id if f.object.photo.attached? %>
        <%= f.input :photo, input_html: {
          direct_upload: true, class: 'fileinput', data: { 
            file: (rails_blob_url(f.object.photo) if f.object.photo.attached?)
          }
        } %>
      </div>
    </div>
  </div>
</div>

app/views/people/_phone_fields.html.erb
<div class="phone nested-fields">
  <div class='row'>
    <%= f.input :number, wrapper_html: { class: 'col-md-3' }, input_html: { class: 'phone_mask' }  %> 
    <%= f.association :phone_type, collection: PhoneType.order(:name), wrapper_html: { class: 'col-md-3' }  %>
    <div class="col-md-2">
      <%= link_to_remove_association f, class: 'btn btn-danger top-32' do %>
        <i class="fa fa-fw fa-times"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/people/edit.html.erb
<%= render 'form', object: @person %>

app/views/people/index.html.erb
<%= search_form_for @q, url: people_path do |f| %>
  <div class="card card-primary card-outline card-info">
    <div class="card-header with-border">
      <div class="row">
        <div class="col-sm-12">
          <div class="input-group">
            <div class="input-group-btn">
              <button type="button" id='btn_filter' class="btn btn-info">
                <i class="fa fa-angle-right"></i>
                Filtrar
              </button>
            </div>
            <%= f.input :name_cont, label: false, required: false,
              placeholder: 'Nome', wrapper: false %>

          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 active-filters "></div>
      </div>
    </div>
    <div class="card-body" style='display: none;'>
      <div class="row">
      </div>
      <%= button_tag type: "submit", class: "btn btn-info" do %>
        <i class="fa fa-search"></i> Pesquisar
      <% end %>
    </div>
  </div>
<% end %>

<%= render 'shared/card_list',
  list: @people,
  sort_all: true,
  show_new: true,
  card_class: 'info',
  table_class: 'bootstrap-table-mobile',
  show_columns: [
    'id',
    'name',
    'cpf',
    'rg',
    'city.name',
    'city.state.name'
  ]
%>

app/views/people/new.html.erb
<%= render 'form', object: @person %>

app/views/people/show.html.erb
<%= render 'shared/show', box_class: 'info', object: @person, excluded_columns: ['user_id', 'workplace', 'business_email', 'person_id', 'ancestry'] %>

<div class="card card-outline card-info">
  <div class="card-header">
    <h3 class="card-title">
      Vínculos de Trabalho
      <%= link_to new_person_employment_path(@person), class: "btn btn-xs btn-info" do %>
        Adicionar <i class="fa fa-plus"></i> 
      <% end %>     
    </h3>
  </div>
  

  <div class="card-body p-0">  
    <table class="bootstrap-table-mobile">
      <thead>
        <tr>
          <th data-align='center'>ID</th>
          <th data-align='center'>Data de Admissão</th>
          <th data-align='center'>Cargo</th>
          <th data-align='center'>Salário Base</th>
          <th data-align='center'>Benefícios</th>
          <th data-align='center'>Fim do Vínculo</th>
          <th data-align='center'>Status</th>
          <th data-align='center'>Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @person.employments.each do |e| %>
          <tr>     
            <td> 
                <%= link_to person_employment_path(@person) do %>
                  <%= e.id%></i> 
                <% end %>    
            </td>    
            <td><%= e.admission_date%></td>
            <td><%= e.occupation.name %></td>
            <td><%= e.base_salary %></td>  
            <td><%= e.total_benefits%></td>  
            <td><%= e.resignation_date %></td>
            <td><%= e.status %></td>
            <td> 
            <%= link_to person_employment_path(@person), class: "btn btn-xs btn-info" do %>
              Visualizar </i> 
            <% end %>    
        </td>    
          </tr>
        <% end %>
      </tbody>
    </table>          
  </div>
</div>

<div class="card card-outline card-info">
  <div class="card-header">
    <h3 class="card-title">
      Matrículas
      <%= link_to new_person_registration_path(@person), class: "btn btn-xs btn-info" do %>
        Adicionar <i class="fa fa-plus"></i> 
      <% end %>     
    </h3>
  </div>

  <div class="card-body p-0">  
    <table class="bootstrap-table-mobile">
      <thead>
        <tr>
          <th data-align='center'>ID</th>
          <th data-align='center'>Data de Matrícula</th>
          <th data-align='center'>Valor</th>
          <th data-align='center'>Dia do Pagamento</th>
          <th data-align='center'>Forma de Pagamento</th>
          <th data-align='center'>Responsável</th>
          <th data-align='center'>Status</th>
          <th data-align='center'>Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @person.registrations.each do |r| %>
          <tr>     
            <td> 
                <%= link_to person_registration_path(@person) do %>
                  <%= r.id %></i> 
                <% end %>    
            </td>    
            <td><%= r.registration_date%></td>
            <td><%= r.value %></td>
            <td><%= r.payment_day %></td>  
            <td><%= r.payment_type.name%></td>  
            <td><%= r.id %></td>
            <td><%= r.id %></td>
            <td> 
            <%= link_to person_registration_path(@person), class: "btn btn-xs btn-info" do %>
              Visualizar </i> 
            <% end %>    
        </td>    
          </tr>
        <% end %>
      </tbody>
    </table>          
  </div>


</div> 






<div class="card card-outline card-info">
  <div class="card-header">
    <h3 class="card-title">
      Documentos
    </h3>
  </div>
  <div class="table">
    <div id="documentos" class='row'>
      <div class="card-body">  
      <table class="table table-bordered table-striped no-padding datatables">
        <thead>
          <tr>
            <th width="15%">Tipo de Documento</th>
            <th>Anexo</th>
          </tr>
        </thead>
        <tbody>
        <% @person.documents.each do |d| %>
          <tr>     
              <td><%= d.document_type.name %> </td>  
              <td><%= link_to "Visualizar", rails_blob_path(d.attachment, disposition: 'preview'), target: :_blank  %></td>                 
          </tr>
        <% end %>
        </tbody>
      </table>          
      </div>
    </div>
  </div>
</div>  